web:
  build: .
  links:
   - mongodb
  environment:
    VIRTUAL_HOST: splatoon.airytail.co
  restart: always
mongodb:
  image: mongo
  command: mongod --smallfiles
  restart: always
  volumes:
    - ./mongodb:/data/db
