web:
  build: .
  links:
   - mongodb
  # ports:
  #  - "80:80"
  environment:
    VIRTUAL_HOST: splatoon-fes.airytail.co
  restart: always
  command: bundle exec ruby web.rb -o 0.0.0.0 -p 80
crawl:
  build: .
  links:
   - mongodb
  restart: always
  command: bundle exec ruby worker.rb
bot:
  build: .
  links:
   - mongodb
  restart: always
  command: bundle exec clockwork bot.rb
mongodb:
  image: mongo
  command: mongod --smallfiles
  restart: always
  volumes:
    - ./mongodb:/data/db
